### ISSUE TITLE
Use simulation template from a different model

### ISSUE THREAD

**Issue by leendertvanwolfswinkel** [nens/threedi-api-qgis-client#284]
Use cases:

1. Run simulation with revision 23 > make some minor edits (e.g. change some pipe diameters) > upload as revision 24 > run the same simulation as before, but now with rev 24
2. User has three schematisations, each containing a variant of the same area (e.g. current situation, with measures nr. 1, with measures nr 2). Wants to run the same simulation with all three variants.

Use case 1 can be solved in the backend, by inheriting all user-defined simulation templates from one revision to the next
Use case 2 could be fixed in the MI and/or the management page

**Comment by leendertvanwolfswinkel** [comment]
@Jonasvsl @Patrick-Nijman any thoughts on this?

**Comment by Jonasvsl** [comment]
Shouldn't the titel be a different schematisation instead of model?

use case 2 I can imagine but it shouldnt make the interface in the MI over complicated 

Jelle argued that use case 2 should also be solved in the front end, but I feel that we should have an endpoint that when called copies the templates from one revision to another. The reason for that is that when a template is simply copied and a user replaces a boundary condition or renames some connection nodes the timeseries of the boundary conditions can be on the wrong node, or at least not expected by the user. 
And added to that: if a user has made 10 templates to test out stuff he selects which ones continue to the next revision, is also a clean up

My other argument for an endpoint is that when users don't use the MI they probably also want to copy templates

**Comment by leendertvanwolfswinkel** [comment]
yes a "clone simulation template" is preferable I think, mainly for validation. 

a simple and clear user interface for use case 2 is definitely a challenge...

**Comment by leendertvanwolfswinkel** [comment]
Not going to implement this, will make matters even more complicated than they already are
