### ISSUE TITLE
Simulation wizard: Add substance concentrations section to Laterals page

### ISSUE THREAD

**Issue by leendertvanwolfswinkel** [nens/threedi-api-qgis-client#538]
Mockup:

<img width="1072" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNSszQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--36c84b50fb079192b613439274f64508092a6449/image.png" alt="image.png" />

Change in design:

- there should be multiple file inputs for different types of substances that have been defined in the Substances page for 1D / 2D

Example script:

[simulate.zip](https://github.com/nens/threedi-api-qgis-client/files/14507760/simulate.zip)

**Comment by hoanphungt** [comment]
Better to wait for #545 and #547 to be merged first to avoid lots of conflicts.

**Comment by hoanphungt** [comment]
@leendertvanwolfswinkel 

Regarding this point:

> there should be multiple file inputs for different types of substances that have been defined in the Substances page for 1D / 2D

I think instead of having 2 file inputs for each substance for 1D and 2D, we only need 1 file input for both of them. That's simpler. What do you think?

The csv file format for the substance concentrations file should look like this:

`id`  |  `timeseries`

in which `id` is the lateral id and `timeseries` is the substance concentrations

**Comment by leendertvanwolfswinkel** [comment]
@hoanphungt that would not be correct, because it is possible to have a 1D lateral with ID 23 **and** a 2D lateral with id 23 in the same simulation, I think?

**Comment by hoanphungt** [comment]
@leendertvanwolfswinkel You are right! It's possible to have 1d and 2d laterals with the same id. I updated the UI.

**Comment by leendertvanwolfswinkel** [comment]
Hi @hoanphungt you can merge the `water_quality` branch to master!
