### ISSUE TITLE
no back button after the new simulations / options screen only cancel

### ISSUE THREAD

**Issue by Jonasvsl** [nens/threedi-api-qgis-client#69]
* threedi-api-qgis-client version: 1.5.0b
* Python version:
* Operating System:

### Description

Describe what you were trying to get done.
Tell us what happened, what went wrong, and what you expected to happen.

### What I Did

```
Paste the command(s) you ran and the output.
If there was a crash, please include the traceback here.
```

**Comment by DamnBack** [comment]
@Jonasvsl This is expected behavior as options dialog is not part of the wizard, but is used to prepare correct wizard structure and fetch data to feed breaches and initial conditions raster lists. Going back to options would introduce much more corner cases and would bring unnecessary code complexity.
